version: "3.3"
services:
  mongo:
    image: 'mongo:4.4.18'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'Marmolada3343'
    ports:
      - '27017:27017'
    volumes:
      - .\data:/data/db