version: "3.3"
services:
  mongo:
    image: 'library/mongo:4.4.18'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE : 'admin'
    ports:
      - '27017:27017'
    volumes:
      - ${MONGO_DATA_VOLUME_PATH}:/data/db