# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-push-docker-image:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build --tag stdallona/plc-testbench-ui:1.0.2 .

      #- run:
      #    name: Publish Docker image
      #    command: docker push stdallona/plc-testbench-ui:1.0.2

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-push-docker-image-workflow:
    jobs:
      - build-and-push-docker-image
